INSERT INTO CUENTA C
(C.EMAIL, C.NOMBRE, C.NVL_CUENTA)
VALUES
('JOSICO@HOTMAIL.COM', 'DREAMHACK_32', 8);

INSERT INTO CUENTA C
(C.EMAIL, C.NOMBRE, C.NVL_CUENTA)
VALUES
('NACHETE@HOTMAIL.COM', '_NACHETE_', 100);

INSERT INTO CUENTA C
(C.EMAIL, C.NOMBRE, C.NVL_CUENTA)
VALUES
('PEPE@HOTMAIL.COM', 'PEPE9432', 2);


INSERT INTO CUENTA C
(C.EMAIL, C.NOMBRE, C.NVL_CUENTA)
VALUES
('PARAGONES@HOTMAIL.COM', 'PARAGON_232', 2);


INSERT INTO CUENTA C
(C.EMAIL, C.NOMBRE, C.NVL_CUENTA, C.FECHA_CREACION)
VALUES
('MANUEH@HOTMAIL.COM', 'MANOLICO232XX', 2, '22/06/2018');


INSERT INTO CUENTA C
(C.EMAIL, C.NOMBRE, C.NVL_CUENTA, C.FECHA_CREACION)
VALUES
('CUENTAFALSA.COM', 'FALSAX232', 2, '22/09/2018');
------


INSERT INTO SER_AMIGOS AM
(AM.EMAIL_AMIGO, AM.EMAIL_CUENTA, AM.FECHA_AMIGOS)
VALUES('PEPE@HOTMAIL.COM', 'PARAGONES@HOTMAIL.COM', '10/09/2019');


INSERT INTO SER_AMIGOS AM
(AM.EMAIL_AMIGO, AM.EMAIL_CUENTA, AM.FECHA_AMIGOS)
VALUES('PEPE@HOTMAIL.COM', 'MANUEH@HOTMAIL.COM', '10/06/2018');


INSERT INTO SER_AMIGOS AM
(AM.EMAIL_AMIGO, AM.EMAIL_CUENTA, AM.FECHA_AMIGOS)
VALUES('MANUEH@HOTMAIL.COM', 'PARAGONES@HOTMAIL.COM', '01/12/2017');


INSERT INTO SER_AMIGOS AM
(AM.EMAIL_AMIGO, AM.EMAIL_CUENTA, AM.FECHA_AMIGOS)
VALUES('CUENTAFALSA.COM', 'PARAGONES@HOTMAIL.COM', '01/12/2018');

----
INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.NOMBRE_GALERIA, G.PUBLICA)
VALUES
(10, 'NACHETE@HOTMAIL.COM', 'MORIGESH', 'S');


INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.NOMBRE_GALERIA, G.PUBLICA)
VALUES
(11, 'NACHETE@HOTMAIL.COM', '2019', 'S');

INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.NOMBRE_GALERIA, G.PUBLICA)
VALUES
(12, 'NACHETE@HOTMAIL.COM', 'MEJORES MOMENTOS TORNEO', 'S');

INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.NOMBRE_GALERIA, G.PUBLICA)
VALUES
(13, 'NACHETE@HOTMAIL.COM', 'FINAL TORNEO', 'S');


INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.NOMBRE_GALERIA, G.PUBLICA)
VALUES
(2, 'PEPE@HOTMAIL.COM', 'MEJORES MOMENTOS 2018', 'N');


INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.NOMBRE_GALERIA, G.PUBLICA)
VALUES
(3, 'PEPE@HOTMAIL.COM', 'WUKONG', 'S');


INSERT INTO GALERIA G
(G.CODIGO_GALERIA, G.EMAIL_CUENTA_GALERIA, G.PUBLICA)
VALUES
(4, 'PARAGONES@HOTMAIL.COM', 'N');


-----


INSERT INTO CAPTURAS C
(C.CODIGO_CAPTURAS, C.EMAIL_CUENTA_CAPTURAS, C.NOMBRE_CAPTURA)
VALUES
(1, 'PEPE@HOTMAIL.COM', 'PAISAJE');


INSERT INTO CAPTURAS C
(C.CODIGO_CAPTURAS, C.EMAIL_CUENTA_CAPTURAS, C.NOMBRE_CAPTURA)
VALUES
(2, 'MANUEH@HOTMAIL.COM', 'GADGET');


INSERT INTO CAPTURAS C
(C.CODIGO_CAPTURAS, C.EMAIL_CUENTA_CAPTURAS, C.NOMBRE_CAPTURA)
VALUES
(3, 'PEPE@HOTMAIL.COM', 'GOLPE VENCEDOR');


-----


INSERT INTO TENER_CAPTURAS TCAP
(TCAP.CODIGO_CAPTURAS_TENER, TCAP.CODIGO_GALERIA_TENER)
VALUES
(2, 1);


INSERT INTO TENER_CAPTURAS TCAP
(TCAP.CODIGO_CAPTURAS_TENER, TCAP.CODIGO_GALERIA_TENER)
VALUES
(1, 1);


INSERT INTO TENER_CAPTURAS TCAP
(TCAP.CODIGO_CAPTURAS_TENER, TCAP.CODIGO_GALERIA_TENER)
VALUES
(3, 2);


-----


INSERT INTO GEMAS G
(G.CODIGO_GEMAS, G.TIPO, G.DESCRIPCION_GEMAS)
VALUES
(1, 'FUEGO', 'GEMA QUE POTENCIA MUCHO EL DAÑO DE HABILIDAD');


INSERT INTO GEMAS G
(G.CODIGO_GEMAS, G.TIPO)
VALUES
(2, 'HIELO');


INSERT INTO GEMAS G
(G.CODIGO_GEMAS, G.TIPO, G.DESCRIPCION_GEMAS)
VALUES
(3, 'VENENO', 'ENVENENA A LOS ENEMIGOS DURANTE CUATRO SEGUNDOS');


INSERT INTO GEMAS G
(G.CODIGO_GEMAS, G.TIPO, G.DESCRIPCION_GEMAS)
VALUES
(60, 'HURACÁN', 'EMPUJA FUERTEMENTE A LOS ENEMIGOS');

----


INSERT INTO CARTAS C
(C.DESCRIPCION_CARTAS, C.NOMBRE_CARTAS)
VALUES
('AL ACTIVARSE PERMITE RETROCEDER EN EL TIEMPO 3 SEG', 'MAQUINA DEL TIEMPO');


INSERT INTO CARTAS C
(C.DESCRIPCION_CARTAS, C.NOMBRE_CARTAS)
VALUES
('PERMITE AL PORTADOR ADENTRASE EN LAS SOMBRAS DURANTE 5SEG, LOS ENEMIGOS
    NO TE PODRÁN VER', 'MORADOR DE LAS TINIEBLAS');


INSERT INTO CARTAS C
(C.DESCRIPCION_CARTAS, C.NOMBRE_CARTAS)
VALUES
('LANZAS UNA DAGA QUE SILENCIA Y ATURDE A LOS ENEMIGOS', 
    'DAGA DEL OLIMPO');
    
    
INSERT INTO CARTAS C
(C.DESCRIPCION_CARTAS, C.NOMBRE_CARTAS)
VALUES
('APARECE UN BRAZO DEL CIELO PORTANDO UN MARTILLO QUE GOLPEA 
CON BRUTALIDAD A TUS ENMIGOS DENTRO DE UN ÁREA', 
    'MARTILLO DE THOR');

---
INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR, DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(80, 'MARTILLO DE THOR', 'NACHETE@HOTMAIL.COM', 60);

INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR, DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(5, 'DAGA DEL OLIMPO', 'NACHETE@HOTMAIL.COM', 3);

INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR, DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(2, 'MAQUINA DEL TIEMPO', 'MANUEH@HOTMAIL.COM', 2);

INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR,DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(2, 'MORADOR DE LAS TINIEBLAS', 'NACHETE@HOTMAIL.COM', 1);

INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR, DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(1, 'DAGA DEL OLIMPO', 'MANUEH@HOTMAIL.COM', 3);


INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR, DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(1, 'MAQUINA DEL TIEMPO', 'MANUEH@HOTMAIL.COM', 2);


INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR,DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(2, 'MORADOR DE LAS TINIEBLAS', 'PEPE@HOTMAIL.COM', 1);


INSERT INTO DESBLOQUEAR DES
(DES.NVL_DESBLOQUEAR, DES.NOMBRE_CARTAS_DESBLOQUEAR, 
    DES.EMAIL_DESBLOQUEAR,DES.CODIGO_GEMAS_DESBLOQUEAR)
VALUES
(2, 'MAQUINA DEL TIEMPO', 'PEPE@HOTMAIL.COM', 2);


-----


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(10, 'MORIGESH', 20);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(20, 'RAMPAGE', 20);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(30, 'SPARROW', 15);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(40, 'THOR', 25);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(60, 'SUPER PABLO', 18);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(30, 'GIDEON', 20);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(40, 'REX', 10);


INSERT INTO HEROES HE
(HE.P_DANYO_HEROE, HE.NOMBRE_HEROE, HE.P_VELOCIDAD_HEROE)
VALUES
(40, 'JULIA', 30);


---

DECLARE
    CONT NUMBER := 1;
    V_HEROE HEROES.NOMBRE_HEROE %TYPE;
    V_CARTA CARTAS.NOMBRE_CARTAS %TYPE;
BEGIN
    WHILE CONT <= 3 LOOP
        IF CONT = 1 THEN 
            V_HEROE := 'SPARROW';
            V_CARTA := 'MAQUINA DEL TIEMPO';
        ELSIF CONT = 2 THEN
            V_HEROE := 'RAMPAGE';
            V_CARTA := 'DAGA DEL OLIMPO';
        ELSIF CONT = 3 THEN
            V_HEROE := 'MORIGESH';
            V_CARTA := 'MORADOR DE LAS TINIEBLAS';
        END IF;
        
        INSERT INTO RECOMENDAR R
        (R.NOMBRE_HEROE_RECOMENDAR, R.CODIGO_GEMAS_RECOMENDAR,
            R.NOMBRE_CARTAS_RECOMENDAR)
        VALUES
        (V_HEROE, CONT, V_CARTA);
        
        CONT := CONT +1;
    END LOOP;   
END;


---


INSERT INTO ASIGNAR A
(A.EMAIL_DESBLOQUEAR_ASIGNAR, A.NOMBRE_CARTAS_DESBLOQUEAR_ASIG,
A.NOMBRE_HEROE_ASIGNAR, A.NVL_DESBLOQUEAR_ASIGNAR, A.CODIGO_GEMAS_DESBLOQUEAR_ASIG)
VALUES
('MANUEH@HOTMAIL.COM', 'DAGA DEL OLIMPO', 'SPARROW', 1, 2);


INSERT INTO ASIGNAR A
(A.EMAIL_DESBLOQUEAR_ASIGNAR, A.NOMBRE_CARTAS_DESBLOQUEAR_ASIG,
A.NOMBRE_HEROE_ASIGNAR, A.NVL_DESBLOQUEAR_ASIGNAR, A.CODIGO_GEMAS_DESBLOQUEAR_ASIG)
VALUES
('MANUEH@HOTMAIL.COM', 'MAQUINA DEL TIEMPO', 'SPARROW', 1, 3);


INSERT INTO ASIGNAR A
(A.EMAIL_DESBLOQUEAR_ASIGNAR, A.NOMBRE_CARTAS_DESBLOQUEAR_ASIG,
A.NOMBRE_HEROE_ASIGNAR, A.NVL_DESBLOQUEAR_ASIGNAR, A.CODIGO_GEMAS_DESBLOQUEAR_ASIG)
VALUES
('PEPE@HOTMAIL.COM', 'MAQUINA DEL TIEMPO', 'MORIGESH', 2, 1);


INSERT INTO ASIGNAR A
(A.EMAIL_DESBLOQUEAR_ASIGNAR, A.NOMBRE_CARTAS_DESBLOQUEAR_ASIG,
A.NOMBRE_HEROE_ASIGNAR, A.NVL_DESBLOQUEAR_ASIGNAR, A.CODIGO_GEMAS_DESBLOQUEAR_ASIG)
VALUES
('PEPE@HOTMAIL.COM', 'MAQUINA DEL TIEMPO', 'RAMPAGE', 2, 2);


----
INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('NACHETE@HOTMAIL.COM', 'RAMPAGE');

INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('NACHETE@HOTMAIL.COM', 'SPARROW');

INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('NACHETE@HOTMAIL.COM', 'MORIGESH');

INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('PEPE@HOTMAIL.COM', 'RAMPAGE');


INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('MANUEH@HOTMAIL.COM', 'RAMPAGE');


INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('PARAGONES@HOTMAIL.COM', 'SPARROW');


INSERT INTO TENER_HEROES TH
(TH.EMAIL_CUENTA_TENER, TH.NOMBRE_HEROE_TENER)
VALUES
('PEPE@HOTMAIL.COM', 'MORIGESH');


----


INSERT INTO HEROE_PERSONALIZADO HPER
(HPER.NOMBRE_HEROE_PERSON, HPER.EMAIL_CUENTA_HEROE_PERSON)
VALUES
('THOR', 'PEPE@HOTMAIL.COM');


INSERT INTO HEROE_PERSONALIZADO HPER
(HPER.NOMBRE_HEROE_PERSON, HPER.EMAIL_CUENTA_HEROE_PERSON, HPER.ELEMENTO)
VALUES
('SUPER PABLO', 'MANUEH@HOTMAIL.COM', 'FUEGO');


----


INSERT INTO MAGOS M
(M.NOMBRE_HEROE_MAGO, M.P_DANYO_MAGICO)
VALUES
('GIDEON', 70);


INSERT INTO MAGOS M
(M.NOMBRE_HEROE_MAGO, M.P_DANYO_MAGICO)
VALUES
('JULIA', 90);


INSERT INTO MAGOS M
(M.NOMBRE_HEROE_MAGO, M.P_DANYO_MAGICO)
VALUES
('REX', 60);


----


INSERT INTO HABILIDADES_ESPECIALES HESP
(HESP.ID_HABILIDAD_ESPECIAL ,HESP.P_CURA_HABILIDAD, 
    HESP.P_DANYO_HABILIDAD, HESP.P_VELOCIDAD_HABILIDAD)
VALUES(1, 20, 30, 20);


INSERT INTO HABILIDADES_ESPECIALES HESP
(HESP.ID_HABILIDAD_ESPECIAL ,HESP.P_CURA_HABILIDAD, 
    HESP.P_DANYO_HABILIDAD, HESP.P_VELOCIDAD_HABILIDAD)
VALUES(2, 12, 43, 26);


INSERT INTO HABILIDADES_ESPECIALES HESP
(HESP.ID_HABILIDAD_ESPECIAL ,HESP.P_CURA_HABILIDAD, 
    HESP.P_DANYO_HABILIDAD, HESP.P_VELOCIDAD_HABILIDAD)
VALUES(53, 19, 80, 10);
