CREATE OR REPLACE PACKAGE PARAGON.GESTION
IS
    PROCEDURE MADRE(CUR_GLOBAL OUT SYS_REFCURSOR, OPCION VARCHAR2, HE_ID NUMBER,
                    VELOCIDAD NUMBER, CURA NUMBER, DANYO NUMBER, NOM_HEROE VARCHAR2);
END;
