CREATE OR REPLACE PACKAGE PARAGON.GESTION
IS
    PROCEDURE MADRE(CUR_GLOBAL OUT SYS_REFCURSOR, OPCION VARCHAR2, HE_ID NUMBER,
                    VELOCIDAD NUMBER, CURA NUMBER, DANYO NUMBER, NOM_HEROE VARCHAR2);
END;
CREATE OR REPLACE PACKAGE BODY PARAGON.GESTION
IS
    PROCEDURE ACTUALIZAR(HE_ID NUMBER, VELOCIDAD NUMBER, CURA NUMBER, 
    DANYO NUMBER, NOM_HEROE VARCHAR2)
    IS
    BEGIN
        UPDATE HABILIDADES_ESPECIALES HE
        SET HE.P_VELOCIDAD_HABILIDAD = VELOCIDAD, HE.P_CURA_HABILIDAD = CURA,
        HE.P_DANYO_HABILIDAD = DANYO, HE.NOMBRE_HEROE_HABILIDAD = NOM_HEROE
        WHERE HE.ID_HABILIDAD_ESPECIAL = HE_ID;
    END;
    PROCEDURE GRABAR(HE_ID NUMBER, VELOCIDAD NUMBER, CURA NUMBER, 
    DANYO NUMBER, NOM_HEROE VARCHAR2)
    IS
    BEGIN
        INSERT INTO HABILIDADES_ESPECIALES HE 
        (HE.ID_HABILIDAD_ESPECIAL, HE.NOMBRE_HEROE_HABILIDAD, HE.P_CURA_HABILIDAD, 
        HE.P_DANYO_HABILIDAD, HE.P_VELOCIDAD_HABILIDAD)
        VALUES
        (HE_ID, NOM_HEROE, VELOCIDAD, CURA, DANYO);
        
        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                ACTUALIZAR(HE_ID, VELOCIDAD, CURA, DANYO, NOM_HEROE);
            WHEN OTHERS THEN
                RAISE_APPLICATION_ERROR(-20100, 'NO EXISTE EL HÉROE PARA EL QUE QUIERES ASIGNAR LA HABILIDAD');
    END;
    PROCEDURE BORRAR(HE_ID NUMBER)
    IS
        CONTADOR NUMBER := 1;
        V_NOMBRE HABILIDADES_ESPECIALES.NOMBRE_HEROE_HABILIDAD%TYPE;
        NO_HABILIDADES EXCEPTION;
    BEGIN
        
        SELECT HE.NOMBRE_HEROE_HABILIDAD
        INTO V_NOMBRE
        FROM HABILIDADES_ESPECIALES HE
        WHERE HE.ID_HABILIDAD_ESPECIAL = HE_ID;
        
        IF V_NOMBRE IS NOT NULL THEN
            SELECT COUNT(*)
            INTO CONTADOR
            FROM HABILIDADES_ESPECIALES HE
            WHERE HE.NOMBRE_HEROE_HABILIDAD = V_NOMBRE;
        END IF;
        
        IF CONTADOR = 0 THEN
            RAISE NO_HABILIDADES;
        END IF;
        
        DELETE HABILIDADES_ESPECIALES HE
        WHERE HE.ID_HABILIDAD_ESPECIAL = HE_ID;
        
        EXCEPTION
            WHEN NO_HABILIDADES THEN
                DELETE MAGOS M
                WHERE M.NOMBRE_HEROE_MAGO = V_NOMBRE;
    END;
    PROCEDURE CONSULTAR(CUR_GLOBAL OUT SYS_REFCURSOR, HE_ID NUMBER)
    IS
        NO_RESULT EXCEPTION;
    BEGIN
        OPEN CUR_GLOBAL FOR SELECT * 
                        FROM HABILIDADES_ESPECIALES HE, MAGOS M
                        WHERE HE.NOMBRE_HEROE_HABILIDAD = M.NOMBRE_HEROE_MAGO
                        AND HE.ID_HABILIDAD_ESPECIAL = HE_ID;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE NO_RESULT;
        END IF;
        EXCEPTION
            WHEN NO_RESULT THEN
                RAISE_APPLICATION_ERROR(-20101, 'NO SE HA ENCONTRADO EL ID');
            WHEN OTHERS THEN
                RAISE_APPLICATION_ERROR(-20100, 'ERROR GENÉRICO');
    END;
    PROCEDURE MADRE(CUR_GLOBAL OUT SYS_REFCURSOR, OPCION VARCHAR2, HE_ID NUMBER,
    VELOCIDAD NUMBER, CURA NUMBER, DANYO NUMBER, NOM_HEROE VARCHAR2)
    IS
    BEGIN
        CASE
            WHEN OPCION = 'GRABAR' THEN
                GRABAR(HE_ID, VELOCIDAD, CURA, DANYO, NOM_HEROE);
            WHEN OPCION = 'BORRAR' THEN
                BORRAR(HE_ID);
            WHEN OPCION = 'CONSULTAR' THEN
                CONSULTAR(CUR_GLOBAL, HE_ID);
        END CASE;
    END;
END GESTION;
